export * from "./types.ts";
export { validateScene, validateTimeline, validateDocument, formatDiagnostics, hasErrors, closest } from "./validate.ts";
export { compileScene, SceneValidationError, generateSortOps } from "./compile/index.ts";
export { scene, defineScene, sceneJson, sceneFromModule } from "./author.ts";
export type { SceneBody } from "./author.ts";
export { sampleFrame, sampleKeyframes, timelineDuration, currentStep, currentCaption, worldPos, ease } from "./timeline.ts";
export { renderFrameSvg, sampleTimes, pathLength } from "./render-svg.ts";
export { checkAnimation, checkTimeline, animStats, explain } from "./check.ts";
export { RUNTIME_SOURCE, renderEmbedHtml } from "./runtime.ts";
export { renderSheetHtml } from "./sheet.ts";
export { scheduleFrames, encodeGif, decodePng, writeVideo, videoFormat, ffmpegAvailable } from "./video.ts";
export type { VideoOptions, VideoResult, ScheduledFrame, RgbaFrame, VideoFormat } from "./video.ts";
